apiVersion: v1
kind: Namespace
metadata:
  name: other-namespace
  label: 
    argocd.argoproj.io/managed-by: openshift-gitops
spec:
  finalizers:
  - kubernetes
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: other
  namespace: openshift-gitops
spec:
  destination:
    namespace: other-namespace
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    chart: quarkus
    repoURL: https://redhat-developer.github.io/redhat-helm-charts
    targetRevision: 0.0.3
  syncPolicy:
    automated:
      prune: false
      selfHeal: true