---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: group-a-p
  namespace: argocd-instance
spec:
  description: group-a 
  sourceRepos:
    - '*'
  destinations:
    - namespace: group-a-namespace
      server: https://kubernetes.default.svc 
    - namespace: argocd-instance
      server: https://kubernetes.default.svc 
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  roles:
    - description: Group to admins to deploy
      groups:
        - group-a
      name: admin
      policies:
        # all
        - >-
          p, proj:group-a-p:admin, applicationsets, *, group-a-p/*, allow
        - >-
          p, proj:group-a-p:admin, applications, *, group-a-p/*, allow
        - >-
          p, proj:group-a-p:admin, repositories, *, group-a-p/*, allow
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: group-b-p
  namespace: argocd-instance
spec:
  description: group-b-p
  sourceRepos:
    - '*'
  destinations:
    - namespace: group-b-namespace
      server: https://kubernetes.default.svc 
    - namespace: argocd-instance
      server: https://kubernetes.default.svc 
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  roles:
    - description: Group to developers to deploy on DEV environment
      groups:
        - group-b
      name: admin
      policies:
        # all
        - >-
          p, proj:group-b-p:admin, applicationsets, *, group-b-p/*, allow
        - >-
          p, proj:group-b-p:admin, applications, *, group-b-p/*, allow
        - >-
          p, proj:group-b-p:admin, repositories, *, group-b-p/*, allow
          
---

