kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-application-controller-custom
  namespace: argocd-instance
rules:
- apiGroups:
  - ""
  - "batch"
  - "apps"
  - "route.openshift.io"
  resources:
  - configmaps
  - endpoints
  - persistentvolumeclaims
  - persistentvolumeclaims/status
  - pods
  - replicationcontrollers
  - replicationcontrollers/scale
  - serviceaccounts
  - services
  - services/status
  - persistentvolumes
  - podtemplates
  - bindings
  - events
  - limitranges
  - namespaces/status
  - pods/log
  - pods/status
  - replicationcontrollers/status
  - resourcequotas
  - resourcequotas/status
  - namespaces
  - secrets
  - routes
  - deployments
  verbs:
  - '*'
- apiGroups:
  - "argoproj.io"
  resources:
  - "*"
  verbs:
  - '*'


