---
kind: Group
apiVersion: user.openshift.io/v1
metadata:
  name: group-all
users:
 - userA
 - userA-view
 - userB
 - userC
 - kubeadmin
---
kind: Group
apiVersion: user.openshift.io/v1
metadata:
  name: group-a
users:
 - userA
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: group-a-admin-binding
  namespace: group-a-na
subjects:
- kind: Group
  name: group-a
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
kind: Group
apiVersion: user.openshift.io/v1
metadata:
  name: group-a-view
users:
 - userA-view
---
kind: Group
apiVersion: user.openshift.io/v1
metadata:
  name: group-b
users:
 - userB
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: group-b-admin-binding
  namespace: group-b-na
subjects:
- kind: Group
  name: group-b
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
