---
apiVersion: v1
kind: Namespace
metadata:
  name: group-a
  labels: 
    argocd.argoproj.io/managed-by: argocd-instance
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  name: group-b
  labels: 
    argocd.argoproj.io/managed-by: argocd-instance
spec:
  finalizers:
  - kubernetes
---