apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: group-a-app
  namespace: argocd-instance
spec:
  destination:
    namespace: group-a-na
    server: 'https://kubernetes.default.svc'
  project: group-a-p
  source:
    helm:
      parameters:
        - name: build.enabled
          value: "false"
        - name: deploy.route.tls.enabled
          value: "true"
        - name: image.name
          value: quay.io/redhatworkshops/gitops-helm-quarkus
    chart: quarkus
    repoURL: https://redhat-developer.github.io/redhat-helm-charts
    targetRevision: 0.0.3