---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: group-a-wrong-project
  namespace: group-a-na
spec:
  project: group-b-p
  source:
    helm:
      parameters:
        - name: build.enabled
          value: "false"
        - name: deploy.route.tls.enabled
          value: "true"
        - name: image.name
          value: quay.io/redhatworkshops/gitops-helm-quarkus
    chart: quarkus
    repoURL: https://redhat-developer.github.io/redhat-helm-charts
    targetRevision: 0.0.3
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: group-a-na
  syncPolicy:
    automated:
      prune: true
      selfHeal: true